name: Docker Image CI

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'tag for this image build'
        required: true
        default: 'staging'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set git tag in output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: name/app    
      -
        name: Check docker-meta
        id: check_meta
        run: |
          echo ${{ steps.meta.outputs.tags }}
          echo ${{ steps.meta.outputs.labels }}
          echo ${{ github.event_name }}
          echo ${{ github.event_name != 'pull_request' }}
          echo ${{ github.event.inputs.image_tag }}
      - 
        name: Test env setup
        id: set_env_pr
        if: startsWith( github.ref, 'refs/tags/v')
        env:
          PILLAR: prod
        run: 
          echo "Should be PR - $PILLAR"
      -
        name: Test Not StartsWith 
        id: set_env_sg
        if: startsWith(github.ref, 'refs/tags/') != true
        env:
          PILLAR: staging
        run: echo "Should be SG - $PILLAR"
      -
        name: Docker meta
        id: meta2
        uses: docker/metadata-action@v3
        with:
          images: name/app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Check docker-meta
        id: check_meta2
        run: |
          echo ${{ steps.meta.outputs.tags }}
          echo ${{ steps.meta.outputs.labels }}
          echo ${{ github.event_name }}
          echo ${{ github.event.inputs.image_tag }}
